name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy CI/CD Demo AWS EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$HOST << 'EOF'
            if [ ! -d "/home/$EC2_USERNAME/node-app" ]; then
              mkdir -p /home/$EC2_USERNAME/node-app
              cd /home/$EC2_USERNAME/node-app
              git clone https://github.com/niravlathiya04/node-CI-CD.git.
            else
              cd /home/$EC2_USERNAME/node-app
              git reset --hard
              git pull origin main
            fi
            npm install
            pm2 start src/app.js --name node-app || pm2 restart node-app
            pm2 save
          EOF
